project:
  type: website
  render:
    - index.qmd
    - notebooks/*.qmd

website:
  title: "DEMからTWI/TPIを計算する"
  repo-url: https://github.com/maple60/dem-twi-r
  repo-actions: [edit, source, issue]
  navbar:
    tools: 
      - icon: github
        href: https://github.com/maple60/dem-twi-r
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Notebooks
        menu:
          - href: notebooks/dem_download.qmd
            text: DEMデータの準備
          - href: notebooks/topographic_wetness_index.qmd
            text: 地形湿潤指数の計算
          - href: notebooks/topographic_position_index.qmd
            text: 地形位置指数の計算
      - href: app/
        text: Shinylive App
      - href: https://maple60-dem-terrain-indices-app.share.connect.posit.cloud/
        text: TWI/TPI計算アプリ

execute:
  freeze: auto

format:
  html:
    lang: ja
    toc: true
    theme: cosmo
