---
title: "DEMからTWI/TPIを計算する"
---

このサイトでは、DEM (数値標高モデル)から地形湿潤指数 (Topographic Wetness Index, TWI)や地形位置指数 (Topographic Position Index, TPI)をR実装する方法についてまとめました。

英語版は上部の**English**タブ、または[English version](en/index.qmd)からアクセスできます。

## Notebooks

DEMデータの準備からTWI/TPIの計算まで、ノートブックでまとめました。
上部の**Notebooks**メニューもしくは以下のリンクからアクセスできます。

- [DEMデータの準備 (未完成)](notebooks/dem_download.qmd)
- [Rによる地形湿潤指数 (TWI)の計算](notebooks/topographic_wetness_index.qmd)
- [Rによる地形位置指数 (TPI)の計算](notebooks/topographic_position_index.qmd)
- [QGISによるTWIとTPIの計算](notebooks/topographic_wetness_index_qgis.qmd)

## App

[Shinylive](https://shiny.posit.co/py/get-started/shinylive.html)という、静的サイト上でShinyアプリを動かす仕組みを使って、合成DEMによるTWIの概念デモを公開しています。
ページ上部の**Shinylive App**もしくは以下のリンクからアクセスできます。

- [TWIの概念デモ](app/)

WhiteboxToolsをShinyliveで動作させるのはどうやら難しそうだったので、完全なアプリケーションではありません。

また、自分のDEMやサンプルデータを使ってTWIやTPIを計算するアプリケーションも公開しています。
ご興味があればお試しください。
ページ上部の**TWI/TPI計算アプリ**もしくは以下のリンクからアクセスできます。

- [TWI/TPI計算](https://maple60-dem-terrain-indices-app.share.connect.posit.cloud/)

こちらのアプリケーションは、[Posit connect cloud](https://posit.co/products/enterprise/connect-cloud)というホスティングサービス上で動作しています。
コードは以下からご確認いただけます。

- [maple60/dem-terrain-indices-app](https://github.com/maple60/dem-terrain-indices-app)

## その他

もしコードを閲覧したり、自分で実行したりしたい場合は、右上のGitHubアイコンからリポジトリにアクセスできます。

また、本リポジトリでは、Rのパッケージ管理に[renv](https://rstudio.github.io/renv/)を使用しています。
リポジトリをクローンした後、Rコンソールで以下のコマンドを実行することで、必要なパッケージをインストールできます。

```{.r}
# install.packages("renv") # まだインストールしていない場合
renv::restore()
```
